spring.application.name=loomlearnproject

# MySQL Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT CONFIG
loomlearn.jwt.secret=loomlearn_project_super_secure_jwt_secret_key_2026_abc123xyz
loomlearn.jwt.expiration=86400000

server.port=8080